### PR TITLE
project.yml mistype error

### PR DESCRIPTION
**Pull request by marcstreeter**
getting 500s from when calling ".../projects/jobserv/builds/../project.yml"

### CODE REVIEW

**Comment by marcstreeter** [comment]
there's something else with this route that is a little off to me. The function signature has two parameters but I only see one from the route. Maybe this is provided elsewhere, so this "fix" may still hit some issues.
```python
@blueprint.route('/builds/<int:build_id>/project.yml', methods=('GET',))
def build_get_project_definition(proj, build_id):
```

**Comment by doanac** [comment]
The "proj" parameter is in the blueprint itself: https://github.com/foundriesio/jobserv/blob/478b876018e6aa52262a008be91c5deb42c4fe8a/jobserv/api/build.py#L14

**Comment by doanac** [comment]
can you fix this line also:

 https://github.com/foundriesio/jobserv/blob/master/tests/test_api_build.py#L63

that will get CI going. And now you know why you can't always trust test-driven-development :)

**Comment by doanac** [comment]
deployed to production `curl https://api.foundries.io/projects/lmp/builds/422/project.yml` works.

**Pull request merged**
