### PR TITLE
Add support for "synchronous" Projects

### PR DESCRIPTION
**Pull request by doanac**
Some CI Projects need to ensure each Build is executed in order. This
change set cleans up the unit-test logic of the current queuing logic
and then adds support for this scenario.

### CODE REVIEW

**Comment by mike-scott** [comment]
@doanac Nit: Seems like the commit title vs. description is conflicting?
https://github.com/foundriesio/jobserv/pull/13/commits/39984187f9c1e553a999783e5f03df0199ba1600

**Comment by doanac** [comment]
>  it seems like that only way to set synchronous_builds, is to configure it when you register a jobserv project, or hand edit the database. Or is there another way in the yaml def I missed?

@EmbeddedAndroid - i got stuck on this as well. The problem with doing from the YAML is that these are defining Triggers for a project and not actual project wide settings. We could allow "patching" this via the API. However, for now we are only ever going to care about this at creation time.

**Comment by EmbeddedAndroid** [comment]
> > it seems like that only way to set synchronous_builds, is to configure it when you register a jobserv project, or hand edit the database. Or is there another way in the yaml def I missed?
> 
> @EmbeddedAndroid - i got stuck on this as well. The problem with doing from the YAML is that these are defining Triggers for a project and not actual project wide settings. We could allow "patching" this via the API. However, for now we are only ever going to care about this at creation time.

Thanks for the explanation, make sense to me. Since we automate the factory deployment, setting ```synchronous_builds=true``` as a default is the way to go.

**Comment by doanac** [comment]
@mike-scott - did a force push. This changes 2 things:

 * commit message is more clear
 * i moved the `AND {tags}` clause of the query before the complex join part to hopefully short-circuit some of the queries that will hit this. eg - if you worker doesn't match there's no sense doing all the complex joins.

**Pull request merged**
