### PR TITLE
github_pr: Look for ok-to-test label

### PR DESCRIPTION
**Pull request by doanac**
It can become a security issue for certain types of CI jobs to allow anyone to trigger a build. This change looks for an "ok-to-test" label on the PR (if one exists for the project) before it will proceed.

Signed-off-by: Andy Doan <andy@foundries.io>

### CODE REVIEW

**Comment by doanac** [comment]
@ricardosalveti @kprosise - heads up on a new CI feature. For public reposistories like meta-lmp, docs, lmp-manifest - we need the ability to label them `ok-to-test` so the CI doesn't get randomly triggered by people. The change is pretty simple:

* if your repository hasn't defined the label "ok-to-test" - things work how they always have
* if you repository has defined the label "ok-to-test" CI won't work until the "ok-to-test" label is added to a PR. Once the label is in place builds get triggered and things like "ci-retest" work.

As you'll see - there's no build triggered. because this PR doesn't have the label.

**Comment by doanac** [comment]
i've added the label, so build 331 was triggered. I can also remove this label and we'll start ignoring the PR until the label is set again.

**Comment by ricardosalveti** [comment]
> @ricardosalveti @kprosise - heads up on a new CI feature. For public reposistories like meta-lmp, docs, lmp-manifest - we need the ability to label them `ok-to-test` so the CI doesn't get randomly triggered by people. The change is pretty simple:

Needed a moment to understand as "ok-to-test" gave the impression that the PR was OK to test (automatically) and not that it required an OK in order for the test to work :-)
 
> * if your repository hasn't defined the label "ok-to-test" - things work how they always have

Ok, so that is just the label from the PR label list, right?

> * if you repository has defined the label "ok-to-test" CI won't work until the "ok-to-test" label is added to a PR. Once the label is in place builds get triggered and things like "ci-retest" work.

Nice.

**Comment by doanac** [comment]
> Ok, so that is just the label from the PR label list, right?

Correct. So, if you add a new label `ok-to-test` to lmp-manifests, jobserv will start requiring PRs to have this label before it will trigger a build.

**Comment by doanac** [comment]
> does this just effect Jobserv, or does it also apply to Github Actions? 

This is just jobserv.

**Pull request merged**
